# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

# When Should you be checking for the code
on:
  push: # When someone pushes a code
    branches: [ main ] # Main is reserved for production ready code.
  pull_request: # When someone makes a pull request
    branches: [ main ]

jobs:
  build:
    # GitHub is going to setup an ubuntu server to run out test with.
    runs-on: ubuntu-latest # Most enterprise software is running linux, more specifically ubuntu.

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x] # We are checking for the versions of node.js

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
